name = "Flugel"
owner = "InfraTeam"
aws_profile = "default"
aws_region = "us-west-2"
aws_ami = "ami-00be885d550dcee43"
aws_instance_type = "t2.micro"
aws_s3_bucket_name = "flugel-bucket-01-hsfh"
aws_bucket_acl = "private"