name: 'Test'

on:
  workflow_dispatch:

jobs:
  terratest:
    name: 'TerraTest'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: List Directory
      run: ls -al
